### PR TITLE
Rebuild Infrastructure

### PR DESCRIPTION
**Pull request by hacxy**
基础设施重构, 外部引入sdk调整为内置sdk

### CODE REVIEW

**Review by Mister-Hope — COMMENTED** [review]
Why are you converting js extensions to ts?

**Comment by hacxy** [comment]
> Why are you converting js extensions to ts?
> 
> try read through the whole page though I point out you a section. https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-bundlers-typescript-runtimes-and-nodejs-loaders. Though in ts5.0, a new option allowImportingTsExtensions is introduced, I don't think there is any benifits that we should prefer it.

我认为这在项目中没有产生任何影响, 我更倾向于后缀.ts而不用.js是因为这个项目本身使用的是ts开发的而不是js, 为什么一定要在ts项目中用.js后缀的导入语句, 这不是很奇怪吗, 更何况目前一切都正常, 尽管只是视觉上的影响我也会觉得不舒服, 另外我正在寻找如何不加文件名后缀也能正常推导类型的配置方案

**Comment by Mister-Hope** [comment]
First I would like to remind you this is a community project instead of a personal one and I have rights to argue with you about the code refactor.

Omit the tech details, generally you are trying to add personal taste into this project by converting "standard, high quality code" to "easy writing code" with styles based on your personal taste. Let's straight to the point, that's bad, and everyone else should discourage that.

I fully understand that your changes are to make you comfortable, but as long as this is not a self-maintained project, and there are others which are talking the same role as you in the project, you should not try to make the code quality "backwards", as that will make **others uncomfortable**.

For a esm/esm-only project, the best practive of its code is targeting esm.

**Comment by hacxy** [comment]
我参考了这篇文章: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c 
发现你的意见是对的, 稍后我会回退这个提交

**Review by Mister-Hope — CHANGES_REQUESTED** [review]

**Pull request merged**
